Enable Py3.9 and Py3.12
Switch to 3.9.20.

Version 3.9.21 was not found in the local cache
Error: Version 3.9.21 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json